mycloud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve

from pan.urls import router

urlpatterns = [
    path('', include('pan.urls')),
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('favicon.ico', serve, {'path': 'favicon.ico'}),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + [
        path('__debug__/', include('debug_toolbar.urls'))
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'pan.views.bad_request_view'
handler403 = 'pan.views.permission_denied_view'
handler404 = 'pan.views.not_found_view'
handler500 = 'pan.views.server_error_view'

pan/urls.py
from django.urls import path

from rest_framework.routers import DefaultRouter

from pan.views import (IndexView, ProfileView, CloudView, HistoryView, BinView,
                       FileDetailView, FileMoveView, FileDeleteView, FileTrashView,
                       FileUploadView, FolderUploadView, FileDownloadView,
                       ShareCreateView, ShareUpdateView, ShareGetView, ShareDelete, ShareLinkView,
                       LoginView, RegisterView, LoginOutView, DuplicatedCheck,
                       AlterAvatarView, AlterPasswordView, AlterInfoView, MsgApprView,
                       CloudViewSet, HistoryViewSet, BinViewSet, FolderViewSet, FileViewSet, NoticeViewSet)

app_name = 'pan'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('cloud', CloudView.as_view(), name='cloud'),
    path('history', HistoryView.as_view(), name='history'),
    path('bin', BinView.as_view(), name='bin'),
    path('detail', FileDetailView.as_view(), name='detail'),
    path('download/<uuid:guid>', FileDownloadView.as_view(), name='download'),
    path('share/<str:signature>', ShareLinkView.as_view(), name='share-link'),
    path('share-get', ShareGetView.as_view(), name='share-get'),
    path('share-create', ShareCreateView.as_view(), name='share-create'),
    path('share-update', ShareUpdateView.as_view(), name='share-update'),
    path('share-delete', ShareDelete.as_view(), name='history-delete'),
    path('file-delete', FileDeleteView.as_view(), name='file-delete'),
    path('file-upload', FileUploadView.as_view(), name='file-upload'),
    path('folder-upload', FolderUploadView.as_view(), name='folder-upload'),
    path('duplicated-check', DuplicatedCheck.as_view(), name='duplicated-check'),
    path('trash', FileTrashView.as_view(), name='trash'),
    path('move', FileMoveView.as_view(), name='move'),
    path('login', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name='register'),
    path('logout', LoginOutView.as_view(), name='logout'),
    path('alter-avatar', AlterAvatarView.as_view(), name='alter-avatar'),
    path('alter-password', AlterPasswordView.as_view(), name='alter-password'),
    path('alter-info', AlterInfoView.as_view(), name='alter-info'),
    path('msg-appr', MsgApprView.as_view(), name='message'),
]

router = DefaultRouter()
router.register('cloud', CloudViewSet, 'api-cloud')
router.register('history', HistoryViewSet, 'api-history')
router.register('bin', BinViewSet, 'api-bin')
router.register('folder', FolderViewSet, 'api-folder')
router.register('file', FileViewSet, 'api-file')
router.register('notice', NoticeViewSet, 'api-notice')

pan/forms.py
from django import forms
from django.contrib.auth.validators import UnicodeUsernameValidator


# 验证表单
class UserBaseForm(forms.Form):
    username = forms.CharField(max_length=150, validators=(UnicodeUsernameValidator,))
    password = forms.CharField(min_length=6, max_length=128)
    remember = forms.BooleanField(required=False)


class InfoForm(forms.Form):
    GENDER = [
        ('0', '女'),
        ('1', '男')
    ]

    gender = forms.ChoiceField(choices=GENDER)
    email = forms.EmailField(required=False)


class PasswordForm(forms.Form):
    oldPassword = forms.CharField(min_length=6, max_length=150)
    newPassword = forms.CharField(min_length=6, max_length=150)


class AvatarForm(forms.Form):
    avatar = forms.ImageField()

pan/views.py
from datetime import timedelta
from json import loads as json_loads
from pathlib import Path
from shutil import rmtree, make_archive, move as file_move

from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.signing import BadSignature, Signer
from django.http import FileResponse
from django.shortcuts import render
from django.utils import timezone
from django.views.generic import View, TemplateView, RedirectView
from rest_framework.permissions import IsAuthenticated
from rest_framework.viewsets import ModelViewSet

from pan.forms import UserBaseForm, InfoForm, AvatarForm, PasswordForm
from pan.models import (GenericFile, UserFile, UserDir, FileShare, ShareRecord,
                        FileType, UserApproval, UserMessage, Notice)
from pan.serializers import FileSerializer, FileShareSerializer, FolderSerializer, NoticeSerializer
from pan.utils import AjaxObj, get_key_signature, get_dir_size, file_size_format


class IndexView(TemplateView):
    """首页"""
    template_name = 'pan/index.html'


class CloudView(LoginRequiredMixin, TemplateView):
    """云盘"""
    template_name = 'pan/cloud.html'


class HistoryView(LoginRequiredMixin, TemplateView):
    """传输历史"""
    template_name = 'pan/history.html'


class BinView(LoginRequiredMixin, TemplateView):
    """回收站"""
    template_name = 'pan/bin.html'


class FileDetailView(LoginRequiredMixin, TemplateView):
    """文件详情"""
    template_name = 'pan/detail.html'


class ProfileView(LoginRequiredMixin, TemplateView):
    """个人信息"""
    template_name = 'pan/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        role = self.request.user.profile.role.role_key
        if role == 'common':
            context['applied'] = UserApproval.objects.filter(state='0', create_by=self.request.user).exists()
        context['role'] = role
        context['record'] = UserApproval.objects.filter(create_by=self.request.user)
        context['message'] = UserMessage.objects.filter(create_by=self.request.user)
        return context


class ShareLinkView(TemplateView):
    """链接获取分享文件"""
    template_name = 'pan/share.html'

    def get_context_data(self, **kwargs):
        signature = self.kwargs.get('signature')
        context = super().get_context_data()
        try:
            share = FileShare.objects.select_related('user_file').get(secret_key=Signer().unsign(signature))
        except BadSignature:
            context['expired'] = True
            return context
        expired = timezone.now() > share.expire_time
        if not expired:
            if self.request.user.is_authenticated:
                ShareRecord.objects.create(file_share=share, recipient=self.request.user)
            else:
                ShareRecord.objects.create(file_share=share, anonymous=self.request.META.get('REMOTE_ADDR'))
            context['file'] = share.user_file
            context['share'] = share
        context['expired'] = expired
        return context


class LoginView(View):
    """登录"""

    def post(self, request):
        form = UserBaseForm(request.POST)
        if form.is_valid():
            user = authenticate(request, username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user:
                login(request, user)
                if not form.cleaned_data['remember']:
                    request.session.set_expiry(0)
                return AjaxObj(msg='登录成功', data=request.session['cloud']).get_response()

            return AjaxObj(500, '失败', {'errors': {'username': ['用户名错误或密码错误']}}).get_response()

        return AjaxObj(500, '失败', {'errors': form.errors}).get_response()


class RegisterView(View):
    """注册"""

    def post(self, request):
        form = UserBaseForm(request.POST)
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return AjaxObj(500, '失败', {'errors': {'username': ['用户名已存在']}}).get_response()

            User.objects.create_user(username=form.cleaned_data['username'],
                                     password=form.cleaned_data['password'])
            return AjaxObj(msg='注册成功').get_response()

        return AjaxObj(500, '失败', {'errors': form.errors}).get_response()


class LoginOutView(RedirectView):
    """登出"""
    pattern_name = 'pan:index'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)


class AlterAvatarView(LoginRequiredMixin, View):
    """修改头像"""

    def post(self, request):
        form = AvatarForm(request.POST, request.FILES)
        if form.is_valid():
            if form.cleaned_data['avatar'].size > settings.MAX_AVATAR_SIZE:
                return AjaxObj(500, f'上传图片不能大于{file_size_format(settings.MAX_AVATAR_SIZE)}').get_response()
            profile = request.user.profile
            profile.avatar = form.cleaned_data['avatar']
            profile.update_by = request.user
            profile.save()
            return AjaxObj(msg='上传成功').get_response()

        return AjaxObj(500, '不合法文件').get_response()


class AlterPasswordView(LoginRequiredMixin, View):
    """修改密码"""

    def post(self, request):
        form = PasswordForm(request.POST)
        if form.is_valid():
            if request.user.check_password(form.cleaned_data['oldPassword']):
                request.user.set_password(form.cleaned_data['newPassword'])
                request.user.save()
                return AjaxObj(msg='修改成功').get_response()

            return AjaxObj(500, '失败', {'errors': {'oldPassword': ['原密码错误']}}).get_response()

        return AjaxObj(500, '失败', {'errors': form.errors}).get_response()


class AlterInfoView(LoginRequiredMixin, View):
    """修改信息"""

    def post(self, request):
        form = InfoForm(request.POST)
        if form.is_valid():
            profile = request.user.profile
            profile.gender = form.cleaned_data['gender']
            profile.update_by = request.user
            request.user.email = form.cleaned_data['email']
            profile.save()
            request.user.save()
            return AjaxObj(msg='更改成功').get_response()

        return AjaxObj(500, '失败', {'errors': form.errors}).get_response()


class MsgApprView(LoginRequiredMixin, View):
    """申请和留言"""

    def post(self, request):
        message = request.POST.get('message').strip()
        if message == '' or message is None:
            return AjaxObj(500, '不合法信息').get_response()
        if request.POST.get('way') == 'apply':
            msg = '成功提交申请'
            UserApproval.objects.create(content=message, create_by=request.user)
        else:
            msg = '感谢你的留言'
            UserMessage.objects.create(content=message, create_by=request.user)
        return AjaxObj(200, msg).get_response()


class FileDownloadView(View):
    """下载文件"""

    def get(self, request, *args, **kwargs):
        uuid = self.kwargs.get('guid')
        root = settings.MEDIA_ROOT
        file = request.user.files.get(file_uuid=uuid)
        if file.file_cate == '0':
            return FileResponse(open(root / file.file_path, 'rb'), as_attachment=True)
        else:
            des = root / Path('zips/cloud')
            file_path = root / file.file_path
            return FileResponse(open(make_archive(des, 'zip', file_path.parent, file_path.stem), 'rb'),
                                as_attachment=True)


class DuplicatedCheck(LoginRequiredMixin, View):
    """检查文件重名"""

    def get(self, request, *args, **kwargs):
        folder = request.user.files.get(file_uuid=request.GET.get('folderUUID', request.session['root']))
        path = Path(folder.file_path) / request.GET.get('uploadName')

        if (Path(settings.MEDIA_ROOT) / path).exists():
            return AjaxObj(500, '目标文件夹内存在同名文件，请注意回收站').get_response()

        return AjaxObj().get_response()


class FileUploadView(LoginRequiredMixin, View):
    """上传文件"""

    def post(self, request):
        file = request.FILES.get('file')
        if file is None:
            return AjaxObj().get_response()

        use = request.session['cloud']['used'] + file.size
        if use > request.session['cloud']['storage']:
            return AjaxObj(500, '剩余空间不足').get_response()

        folder = request.user.files.get(file_uuid=request.POST.get('folderUUID', request.session['root']))
        file_path = Path(folder.file_path) / file.name
        file_type = FileType.objects.get_or_create(suffix=Path(file.name).suffix, defaults={'type_name': '未知'})[0]
        dirs = []

        with open(settings.MEDIA_ROOT / file_path, 'wb') as f:
            for chunk in file.chunks():
                f.write(chunk)
        UserFile(file_name=file.name, file_type=file_type, file_size=file.size, file_path=file_path,
                 folder=folder, create_by=request.user).save()

        # 更新父文件夹大小
        while folder is not None:
            folder.file_size = folder.file_size + file.size
            folder.update_by = request.user
            dirs.append(folder)
            folder = folder.folder
        UserDir.objects.bulk_update(dirs, ('file_size', 'update_by'))

        request.session['cloud']['used'] = use
        return AjaxObj(200, '成功上传文件').get_response()


class FolderUploadView(LoginRequiredMixin, View):
    """上传文件夹"""

    def post(self, request):
        files = request.FILES.getlist('files')
        paths = request.POST.getlist('paths')

        if files is None or paths is None:
            return AjaxObj().get_response()

        path_nums = len(paths)
        if path_nums * 2 > settings.DATA_UPLOAD_MAX_NUMBER_FIELDS:
            return AjaxObj(500, f'上传条目数超过{settings.DATA_UPLOAD_MAX_NUMBER_FIELDS}限制').get_response()

pan/templates/pan/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.bootcdn.net/ajax/libs/mdb-ui-kit/3.9.0/mdb.min.css" rel="stylesheet">
    <link href="https://cdn.bootcdn.net/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
    <link href="{% static 'pan/css/common.css' %}" rel="stylesheet">
    {% block styles %}{% endblock %}{# css样式 #}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<header>
    {# 侧边栏 #}
    <div class="offcanvas offcanvas-start bg-white border-end-0 shadow-2" data-mdb-scroll="true"
         data-mdb-backdrop="false" tabindex="-1" id="sidebar" style="width: 240px; height: 100vh; z-index: 1035">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title">
                <a class="icon-link" href="{% url 'pan:index' %}" style="padding: 0.625rem 1.5rem 0.5rem;">
                    <i class="fab fa-cloudscale fa-3x"></i>
                </a>
            </h5>
            <a class="icon-link d-block d-lg-none" data-mdb-dismiss="offcanvas"
               style="padding: 0.625rem 1.5rem 0.5rem;">
                <i class="fas fa-times fa-2x"></i>
            </a>
        </div>
        <div class="offcanvas-body d-flex flex-column mt-5">
            <div class="flex-shrink-0 nav nav-tabs flex-column align-items-right" id="v-tabs-tab">
                {% block sidenavs %}
                    <a class="nav-link fs-6" id="cloudTab" href="{% url 'pan:cloud' %}">
                        <i class="fas fa-cloud me-2"></i>我的云盘
                    </a>
                    <a class="nav-link fs-6" id="historyTab" href="{% url 'pan:history' %}">
                        <i class="fas fa-history me-2"></i>传输历史
                    </a>
                    <a class="nav-link fs-6" id="binTab" href="{% url 'pan:bin' %}">
                        <i class="fas fa-trash me-2"></i>回收站
                    </a>
                {% endblock %}
            </div>
            <div class="mt-auto">
                <div class="card" id="memory">
                    <div class="card-body">
                        <div class="card-text">
                            <i class="fas fa-cog me-2"></i>
                            <small class="text-muted">
                                我的容量：<br>
                                <sapn id="storage"></sapn>
                                / <span id="used"></span>
                            </small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {# 侧边栏 #}
    {# 导航栏 #}
    <nav class="navbar sidenav navbar-expand-lg navbar-light bg-white fixed-top shadow-2">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" id="sidebarBtn" data-mdb-toggle="offcanvas"
                    data-mdb-target="#sidebar">
                <i class="fas fa-bars"></i>
            </button>
            <div class="d-none d-sm-flex input-group w-auto">
                <input type="search" class="form-control rounded search" placeholder="搜索" autocomplete="off"/>
                <span class="input-group-text border-0">
                    <i class="fas fa-search"></i>
                </span>
            </div>
            <div class="navbar-nav flex-row ms-auto align-items-center">
                <a class="nav-link px-2 dropdown-toggle hidden-arrow" data-mdb-toggle="dropdown" id="notice">
                    <i class="fas fa-bell"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-end"></ul>
                <a class="nav-link px-2" data-mdb-toggle="tooltip" data-mdb-placement="bottom" title="后续更新">
                    <i class="fas fa-question-circle"></i>
                </a>
                <a class="nav-link px-2" href="{% url 'pan:profile' %}" data-mdb-toggle="tooltip"
                   data-mdb-placement="bottom" title="账户">
                    <img src="{{ user.profile.avatar.url }}" class="rounded-circle" height="25" width="25"
                         alt="avatar"/>
                </a>
            </div>
        </div>
    </nav>
    {# 导航栏 #}
</header>
<main class="main-container">
    <div class="container-lg px-lg-4">
        {% block search %}
        <div class="input-group d-flex d-sm-none">
            <input type="search" class="form-control rounded search" placeholder="搜索" autocomplete="off"/>
            <span class="input-group-text border-0">
                <i class="fas fa-search"></i>
            </span>
        </div>
        {% endblock %}
        {% block content %}{% endblock %}
    </div>
</main>
{# 确认框 #}
<div class="modal fade" id="modal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body text-center">
                <h5 class="mb-4 modal-title"></h5>
                <div class="modal-btn">
                    <button class="btn btn-light" data-mdb-dismiss="modal">取消</button>
                    <button class="btn btn-danger">确定</button>
                </div>
            </div>
        </div>
    </div>
</div>
{# 确认框 #}
{# alert #}
<div class="alert alert-info translate-middle px-2 py-1 fade hide" id="alert"
     style="z-index: 1; position: absolute; left: 50%; top: -20%">
    <i class="fas fa-check-circle"></i><span class="ps-2 alert-content">复制成功</span>
</div>
{# alert #}
{# 验证通知 #}
<div class="position-fixed bottom-0 end-0 p-3" style="z-index: 5">
    <div id="toast" class="toast fade hide">
        <div class="toast-header">
            <i></i>
            <button type="button" class="ms-auto btn-close" data-mdb-dismiss="toast"></button>
        </div>
        <div class="toast-body"></div>
    </div>
</div>
{# 验证通知 #}
{% block componets %}{% endblock %} {# 组件 #}
<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.bootcdn.net/ajax/libs/mdb-ui-kit/3.9.0/mdb.min.js"></script>
<script src="{% static 'pan/js/utils.js' %}"></script>
<script src="{% static 'pan/js/config.js' %}"></script>
<script src="{% static 'pan/js/responsive.js' %}"></script>
{% block scripts %}{% endblock %}{# js文件 #}
</body>
</html>

pan/templates/pan/bin.html
{% extends 'pan/base.html' %}
{% load static %}

{% block styles %}
    <link href="https://cdn.staticfile.org/bootstrap-table/1.19.1/bootstrap-table.min.css" rel="stylesheet">
{% endblock %}

{% block title %}回收站{% endblock %}

{% block sidenavs %}
    <a class="nav-link fs-6" id="cloudTab" href="{% url 'pan:cloud' %}">
        <i class="fas fa-cloud me-2"></i>我的云盘
    </a>
    <a class="nav-link fs-6" id="historyTab" href="{% url 'pan:history' %}">
        <i class="fas fa-history me-2"></i>传输历史
    </a>
    <a class="nav-link fs-6 active" id="binTab" href="{% url 'pan:bin' %}">
        <i class="fas fa-trash me-2"></i>回收站
    </a>
{% endblock %}

{% block content %}
    <div id="toolbar">
        <div class="float-end btn-group shadow-0" role="group">
            <button type="button" id="recycleBtn" class="btn btn-light" data-mdb-toggle="tooltip"
                            data-mdb-placement="bottom" title="恢复"><i class="fas fa-undo-alt"></i></button>
            <button type="button" id="delBtn" class="btn btn-light" data-mdb-toggle="tooltip"
                            data-mdb-placement="bottom" title="删除"><i class="fas fa-trash"></i></button>
            <button type="button" id="sortBy" class="btn btn-light dropdown-toggle hidden-arrow "
                    data-mdb-toggle="dropdown" data-mdb-placement="bottom" data-custom-sort="create_time">上传时间
            </button>
            <button type="button" id="sortOrder" class="btn btn-light px-2"
                    data-mdb-placement="bottom"
                    data-custom-order="desc"><i class="fas fa-sort-down"></i>
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item sort" data-custom-sort="file_name"
                       href="javascript:void (0)">文件名</a></li>
                <li><a class="dropdown-item sort" data-custom-sort="file_size"
                       href="javascript:void (0)">文件大小</a></li>
                <li><a class="dropdown-item sort" data-custom-sort="create_time"
                       href="javascript:void (0)">上传时间</a></li>
            </ul>
        </div>
        <div class="pb-3 card" style="clear: both"></div>
    </div>
    <table id="binTable"></table>
{% endblock %}

{% block scripts %}
    <script src="https://cdn.staticfile.org/bootstrap-table/1.19.1/bootstrap-table.min.js"></script>
    <script src="https://cdn.staticfile.org/bootstrap-table/1.19.1/locale/bootstrap-table-zh-CN.min.js"></script>
    <script src="//at.alicdn.com/t/font_2926309_gvlwiirwihf.js"></script>
    <script src="{% static 'pan/js/common-table.js' %}"></script>
    <script src="{% static 'pan/js/bin-table.js' %}"></script>
{% endblock %}

pan/templates/pan/history.html
{% extends 'pan/base.html' %}
{% load static %}

{% block styles %}
    <link href="https://cdn.staticfile.org/bootstrap-table/1.19.1/bootstrap-table.min.css" rel="stylesheet">
{% endblock %}

{% block title %}传输历史{% endblock %}

{% block sidenavs %}
    <a class="nav-link fs-6" id="cloudTab" href="{% url 'pan:cloud' %}">
        <i class="fas fa-cloud me-2"></i>我的云盘
    </a>
    <a class="nav-link fs-6 active" id="historyTab" href="{% url 'pan:history' %}">
        <i class="fas fa-history me-2"></i>传输历史
    </a>
    <a class="nav-link fs-6" id="binTab" href="{% url 'pan:bin' %}">
        <i class="fas fa-trash me-2"></i>回收站
    </a>
{% endblock %}

{% block content %}
    <div id="toolbar">
        <div class="float-end btn-group shadow-0" role="group">
            <button type="button" id="delBtn" class="btn btn-light" data-mdb-toggle="tooltip"
                    data-mdb-placement="bottom" title="删除"><i class="fas fa-trash"></i></button>
            <button type="button" id="sortBy" class="btn btn-light dropdown-toggle hidden-arrow "
                    data-mdb-toggle="dropdown" data-mdb-placement="bottom" data-custom-sort="create_time">创建时间
            </button>
            <button type="button" id="sortOrder" class="btn btn-light px-2"
                    data-mdb-placement="bottom"
                    data-custom-order="desc"><i class="fas fa-sort-down"></i>
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item sort" data-custom-sort="expire_time"
                       href="javascript:void (0)">过期时间</a></li>
                <li><a class="dropdown-item sort" data-custom-sort="create_time"
                       href="javascript:void (0)">创建时间</a></li>
            </ul>
        </div>
        <div class="pb-3 card" style="clear: both"></div>
    </div>
    <table id="historyTable"></table>
{% endblock %}

{% block componets %}{# 链接设置 #}
    <div class="modal fade" id="shareModal" data-custom-id="">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header border-bottom-0">
                    <h5 class="modal-title">链接设置</h5>
                    <button type="button" class="btn-close" data-mdb-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6 border-end">
                            <div class="mb-3">
                                <p>链接分享</p>
                                <div class="bg-image hover-overlay ripple copy-text text-center w-100">
                                    <div class="border rounded text-truncate py-2 px-1" id="shareLink"></div>
                                    <a href="javascript:void(0)" class="text-dark copy-mask">
                                        <div class="mask rounded p-2" style="background-color: #EEEEEE">复制</div>
                                    </a>
                                </div>
                            </div>
                            <div class="mb-3">
                                <p>口令分享</p>
                                <div class="bg-image hover-overlay ripple copy-text text-center">
                                    <div class="w-100 border rounded py-2 px-1" id="shareKey"></div>
                                    <a href="javascript:void(0)" class="text-dark copy-mask">
                                        <div class="mask rounded p-2" style="background-color: #EEEEEE">复制</div>
                                    </a>
                                </div>
                            </div>
                            <div class="mb-3 text-center">
                                <button class="btn btn-info">一键复制</button>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <p>设置</p>
                            <div class="d-flex align-items-center mb-3">
                                <div>有效期</div>
                                <div class="dropdown ms-auto">
                                    <sapn class="me-1" id="delta" data-custom-delta="">请选择</sapn>
                                    <a class="icon-link hidden-arrow" href="javascript:void (0)"
                                       data-mdb-toggle="dropdown">
                                        <i class="fas fa-angle-down"></i>
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <li><a class="dropdown-item" data-custom-delta="1"
                                               href="javascript:void (0)">1天</a></li>
                                        <li><a class="dropdown-item" data-custom-delta="7"
                                               href="javascript:void (0)">7天</a></li>
                                        <li><a class="dropdown-item" data-custom-delta="30" href="javascript:void (0)">30天</a>
                                        </li>
                                        <li><a class="dropdown-item" data-custom-delta="999" href="javascript:void (0)">永久有效</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="mb-3">
                                <p>补充描述</p>
                                <div class="form-outline">
                                    <textarea class="form-control border" id="summary" rows="3"
                                              maxlength="100"></textarea>
                                    <label class="form-label copy-text">此信息将展示给分享的用户</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}{# 链接设置 #}

{% block scripts %}
    <script src="https://cdn.staticfile.org/bootstrap-table/1.19.1/bootstrap-table.min.js"></script>
    <script src="https://cdn.staticfile.org/bootstrap-table/1.19.1/locale/bootstrap-table-zh-CN.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/clipboard.js/2.0.8/clipboard.min.js"></script>
    <script src="//at.alicdn.com/t/font_2926309_gvlwiirwihf.js"></script>
    <script src="{% static 'pan/js/common-table.js' %}"></script>
    <script src="{% static 'pan/js/history-table.js' %}"></script>
{% endblock %}